steps:
  - name: gcr.io/cloud-builders/docker
    id: spanner-emulator
    args: ['run', '-d', '-p', '9010:9010', '-p', '9020:9020', '--network=cloudbuild', '--name=spanner-emulator', 'gcr.io/cloud-spanner-emulator/emulator:0.8.0']
    waitFor: ['-']
  - name: jwilder/dockerize:0.6.1
    args: ['dockerize', '-timeout=60s', '-wait=tcp://spanner-emulator:9010']
    waitFor: ['spanner-emulator']
  - name: 'golang:1.14-stretch'
    id: setup
    entrypoint: 'bash'
    args:
      - './setup.sh'
    env:
      - 'GO111MODULE=on'
      - 'GOBIN=/workspace/build-cmd'
    waitFor: ['-']
  - name: 'golang:1.14-stretch'
    entrypoint: 'bash'
    args:
      - './test.sh'
    env:
      - 'GO111MODULE=on'
      - 'GOBIN=/workspace/build-cmd'
      - 'SPANNER_EMULATOR_HOST=spanner-emulator:9010'
    waitFor: ['spanner-emulator', 'setup']

