steps:
  - name: gcr.io/cloud-builders/docker
    id: spanner-emulator
    args: ['run', '-d', '-p', '9010:9010', '-p', '9020:9020', '--network=cloudbuild', '--name=spanner-emulator', 'gcr.io/cloud-spanner-emulator/emulator:1.3.0']
    waitFor: ['-']
  - name: jwilder/dockerize:0.6.1
    args: ['dockerize', '-timeout=60s', '-wait=tcp://spanner-emulator:9010']
    waitFor: ['spanner-emulator']
  - name: 'golang:1.19-buster'
    id: setup
    entrypoint: 'bash'
    args:
      - './setup.sh'
    env:
      - 'GO111MODULE=on'
      - 'GOBIN=/workspace/build-cmd'
    waitFor: ['-']
  - name: 'golang:1.19-buster'
    entrypoint: 'bash'
    args:
      - './lint.sh'
    env:
      - 'GO111MODULE=on'
      - 'GOBIN=/workspace/build-cmd'
      - 'SPANNER_EMULATOR_HOST=spanner-emulator:9010'
      - 'GCPBOX_CI_PROJECT=$PROJECT_ID'
    waitFor: ['setup']
  - name: 'golang:1.19-buster'
    entrypoint: 'bash'
    args:
      - './test.sh'
    env:
      - 'GO111MODULE=on'
      - 'GOBIN=/workspace/build-cmd'
      - 'SPANNER_EMULATOR_HOST=spanner-emulator:9010'
      - 'GCPBOX_CI_PROJECT=$PROJECT_ID'
    secretEnv: ['GCPBOX_ORGANIZATION', 'GCPBOX_SCOPING_PROJECT']
    waitFor: ['spanner-emulator', 'setup']
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/GCPBOX_ORGANIZATION/versions/1
    env: 'GCPBOX_ORGANIZATION'
  - versionName: projects/$PROJECT_ID/secrets/GCPBOX_SCOPING_PROJECT/versions/1
    env: 'GCPBOX_SCOPING_PROJECT'

