// Code generated by "stringer -type StorageClassType storage_class_type.go"; DO NOT EDIT.

package storage

import "fmt"

const _StorageClassType_name = "MultiRegionalRegionalNearlineColdlineStandardDurableReducedAvailability"

var _StorageClassType_index = [...]uint8{0, 13, 21, 29, 37, 45, 71}

func (i StorageClassType) String() string {
	if i < 0 || i >= StorageClassType(len(_StorageClassType_index)-1) {
		return fmt.Sprintf("StorageClassType(%d)", i)
	}
	return _StorageClassType_name[_StorageClassType_index[i]:_StorageClassType_index[i+1]]
}
